const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const base = process.env.PETWAYMARK_WEB_URL || 'http://127.0.0.1:8766';
(async () => {
 const browser = await chromium.launch({...(process.env.PETWAYMARK_BROWSER_PATH ? {executablePath:process.env.PETWAYMARK_BROWSER_PATH} : {}),headless:true,args:['--no-sandbox']});
 const page = await browser.newPage();
 const errors=[]; page.on('pageerror',e=>errors.push(String(e)));
 const remote=[]; page.on('request',r=>{if(!r.url().startsWith(base))remote.push(r.url())});
 await page.goto(base+'/?example=owner');
 await page.locator('form button[type=submit]').first().click();
 await page.waitForURL('**/assess');
 await page.locator('#result-title').waitFor();
 assert.match(await page.locator('#result-title').innerText(),/未覆盖/);
 const codes=await page.locator('section > p.codes').innerText();
 await page.locator('#language').click();
 await page.waitForFunction(()=>document.documentElement.lang==='en');
 assert.equal(await page.locator('select[name=accompaniment]').inputValue(),'owner');
 assert.equal(await page.locator('input[name=entry_at]').inputValue(),'2026-11-10');
 assert.equal(await page.locator('section > p.codes').innerText(),codes);
 const downloadPromise=page.waitForEvent('download');
 await page.locator('button[name=output]').click();
 const download=await downloadPromise;
 assert.equal(download.suggestedFilename(),'petwaymark-preview.json');
 const fs=require('node:fs');const json=JSON.parse(fs.readFileSync(await download.path(),'utf8'));
 assert.equal(json.status,'unsupported');assert.equal(json.booking_confirmed,false);
 await page.evaluate(()=>{window.print=()=>{window.didPrint=true}});
 await page.locator('#print').click();
 assert.equal(await page.locator('.printable').getAttribute('open'),'');
 assert.equal(await page.evaluate(()=>window.didPrint),true);
 await page.emulateMedia({media:'print'});
 await page.pdf({path:'/tmp/petwaymark-browser-print.pdf',format:'A4'});
 await page.emulateMedia({media:'screen'});
 await page.locator('.printable').evaluate(el => {el.open=false});
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:'/tmp/petwaymark-browser-mobile.png',fullPage:false});
 for (const example of ['eu-owner','eu-boarding']) {
  await page.goto(base+'/?example='+example);
  await page.locator('form details > summary').first().click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.locator('form button[type=submit]').first().click();
  await page.waitForURL('**/assess');
  await page.locator('#result-title').waitFor();
  const euCodes=await page.locator('section > p.codes').innerText();
  assert.match(await page.locator('section').innerText(),/local_overlay_uncovered/);
  assert.match(await page.locator('section').innerText(),/2026_131_independent_review_pending/);
  await page.locator('#language').click();
  await page.waitForFunction(()=>document.documentElement.lang==='en');
  assert.equal(await page.locator('section > p.codes').innerText(),euCodes);
  assert.equal(await page.locator('select[name=owner_moving]').inputValue(),example==='eu-owner'?'true':'false');
  assert.equal(await page.locator('input[name=owner_entry_at]').inputValue(),example==='eu-owner'?'2026-11-10':'');
  const pending=page.waitForEvent('download');
  await page.locator('button[name=output]').click();
  const file=await pending;
  const result=JSON.parse(fs.readFileSync(await file.path(),'utf8'));
  assert.equal(result.status,'unsupported');assert.equal(result.booking_confirmed,false);
  assert.equal(result.classification_resolved,example==='eu-owner');
  assert.equal(result.eu_inventory.members.length,27);
  assert.equal(result.eu_inventory.members.filter(m=>m.status==='local_overlay_uncovered').length,24);
  assert.deepEqual(result.candidates,[]);
  if (example==='eu-boarding') {
   assert.deepEqual(result.explanations,[]);assert.deepEqual(result.draft_diagnostics,[]);
   assert(result.reason_codes.includes('owner_not_moving_separate_classification'));
  } else {
   assert(result.draft_diagnostics.some(d=>d.outcome==='model_date_consistent'));
  }
  await page.evaluate(()=>{window.print=()=>{window.didPrint=true}});
  await page.locator('#print').click();
  assert.equal(await page.evaluate(()=>window.didPrint),true);
  assert.match(await page.locator('.printable').innerText(),/eu.577.ahc/);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 }
 await page.pdf({path:'/tmp/petwaymark-eu-browser-print.pdf',format:'A4'});
 for (const direction of ['us','eu']) {
  await page.goto(base+'/?example=outbound-'+direction);
  await page.locator('#outbound-inputs > summary').click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  // Use native fields to create a real appointment conflict.
  if (direction==='eu') await page.locator('input[name=certificate_at]').fill('2026-10-30');
  await page.locator('form button[type=submit]').first().click();
  await page.waitForURL('**/assess');
  await page.locator('#result-title').waitFor();
  const codes=await page.locator('section > p.codes').innerText();
  if (direction==='eu') assert.match(codes,/appointment.certificate-window.date_window_conflict/);
  await page.locator('#language').click();
  await page.waitForFunction(()=>document.documentElement.lang==='en');
  assert.equal(await page.locator('section > p.codes').innerText(),codes);
  assert.equal(await page.locator('input[name=certificate_at]').inputValue(),direction==='eu'?'2026-10-30':'2026-11-05');
  const pending=page.waitForEvent('download');await page.locator('button[name=output]').click();
  const file=await pending;const result=JSON.parse(fs.readFileSync(await file.path(),'utf8'));
  assert.equal(result.status,'unsupported');assert.equal(result.booking_confirmed,false);
  assert.equal(result.classification_resolved,true);
  assert(result.timeline.some(e=>e.event_id==='certificate.issue'));
  assert(result.timeline.some(e=>e.event_id==='certificate.endorsement'));
  assert(result.document_checklist.every(d=>d.custody_confirmed===false));
  await page.evaluate(()=>{window.print=()=>{window.didPrint=true}});
  await page.locator('#print').click();assert.equal(await page.evaluate(()=>window.didPrint),true);
  assert.match(await page.locator('.printable').innerText(),/pending_arrangement/);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.emulateMedia({media:'print'});
  await page.pdf({path:'/tmp/petwaymark-outbound-'+direction+'.pdf',format:'A4'});
  await page.emulateMedia({media:'screen'});
 }
 assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);
 console.log('PASS: CN/US and EU browser language/input parity, owner-not-moving gate, 27/24-member gaps, JSON download, checklist print/PDF, mobile overflow, CN outbound timelines, appointment conflict, zero external requests.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
