const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const base = process.env.PETWAYMARK_WEB_URL || 'http://127.0.0.1:8766';
(async () => {
 const browser = await chromium.launch({...(process.env.PETWAYMARK_BROWSER_PATH ? {executablePath:process.env.PETWAYMARK_BROWSER_PATH} : {}),headless:true,args:['--no-sandbox']});
 const page = await browser.newPage();
 const errors=[]; page.on('pageerror',e=>errors.push(String(e)));
 const remote=[]; page.on('request',r=>{if(!r.url().startsWith(base))remote.push(r.url())});
 await page.goto(base+'/?example=owner');
 await page.locator('form button[type=submit]').first().click();
 await page.waitForURL('**/assess');
 await page.locator('#result-title').waitFor();
 assert.match(await page.locator('#result-title').innerText(),/未覆盖/);
 const codes=await page.locator('section > p.codes').innerText();
 await page.locator('#language').click();
 await page.waitForFunction(()=>document.documentElement.lang==='en');
 assert.equal(await page.locator('select[name=accompaniment]').inputValue(),'owner');
 assert.equal(await page.locator('input[name=entry_at]').inputValue(),'2026-11-10');
 assert.equal(await page.locator('section > p.codes').innerText(),codes);
 const downloadPromise=page.waitForEvent('download');
 await page.locator('button[name=output]').click();
 const download=await downloadPromise;
 assert.equal(download.suggestedFilename(),'petwaymark-preview.json');
 const fs=require('node:fs');const json=JSON.parse(fs.readFileSync(await download.path(),'utf8'));
 assert.equal(json.status,'unsupported');assert.equal(json.booking_confirmed,false);
 await page.evaluate(()=>{window.print=()=>{window.didPrint=true}});
 await page.locator('#print').click();
 assert.equal(await page.locator('.printable').getAttribute('open'),'');
 assert.equal(await page.evaluate(()=>window.didPrint),true);
 await page.emulateMedia({media:'print'});
 await page.pdf({path:'/tmp/petwaymark-browser-print.pdf',format:'A4'});
 await page.emulateMedia({media:'screen'});
 await page.locator('.printable').evaluate(el => {el.open=false});
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:'/tmp/petwaymark-browser-mobile.png',fullPage:false});
 assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);
 console.log('PASS: browser language/input parity, JSON download, checklist print/PDF, mobile overflow, zero external requests.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
