// Verification tooling only. Owner pages have no runtime dependencies.
// See docs/development.md for offline browser verification.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const root=path.resolve(process.env.PETWAYMARK_PAGES_ROOT || '_site');
const home=pathToFileURL(path.join(root,'index.html')).href;
const result=pathToFileURL(path.join(root,'result.html')).href;
(async()=>{
 const artifacts=path.resolve(process.env.PETWAYMARK_ARTIFACTS || '/tmp/petwaymark-build-checks'); fs.mkdirSync(artifacts,{recursive:true});
 const browser=await chromium.launch({headless:true, ...(process.env.PETWAYMARK_CHROME ? {executablePath:process.env.PETWAYMARK_CHROME} : {})});
 const page=await browser.newPage({viewport:{width:390,height:844}});
 const remote=[]; page.on('request',r=>{if(/^https?:/.test(r.url()))remote.push(r.url());});
 const navigate=async url=>{await page.goto('about:blank');await page.goto(url);};
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const checks=[];
 const check=(name)=>checks.push(name);
 await navigate(home);
 assert.equal(await page.locator('.selection-area .choice').count(),3);
 await page.click('#pet');assert.equal(await page.locator('[data-pet]').count(),2);await page.click('[data-pet="cat"]');check('首页三个选择框；宠物只有狗、猫');
 await page.click('#origin');assert.equal(await page.locator('#city-step').isVisible(),false);assert.equal(await page.locator('#area-step').isVisible(),false);
 await page.selectOption('#country','CN');assert.equal(await page.locator('#city-step').isVisible(),true);assert.equal(await page.locator('#area-step').isVisible(),false);
 await page.selectOption('#city','上海市');assert.equal(await page.locator('#area-step').isVisible(),true);await page.selectOption('#area','徐汇区');
 await page.selectOption('#city','北京市');assert.equal(await page.inputValue('#area'),'');assert.equal(await page.locator('#confirm-place').isDisabled(),true);
 await page.selectOption('#country','FR');assert.equal(await page.inputValue('#city'),'');assert.equal(await page.locator('#area-step').isVisible(),false);check('选上级才显示下级；改国家/城市清空子级');
 await page.selectOption('#country','CN');await page.fill('#place-search','黄山');assert.equal(await page.locator('#city option').count(),2);
 await page.selectOption('#city','黄山市（安徽省）');await page.fill('#place-search','屯溪');assert.equal(await page.locator('#area option').count(),2);await page.selectOption('#area','屯溪区');await page.click('#confirm-place');check('城市与乡镇搜索按父级筛选');
 await page.click('#origin');await page.selectOption('#country','US');await page.keyboard.press('Escape');assert.match(await page.textContent('#origin-value'),/屯溪区/);assert.equal(await page.evaluate(()=>document.activeElement.id),'origin');check('Escape 取消不覆盖已确认地点并恢复焦点');
 await page.click('#destination');await page.selectOption('#country','CN');await page.selectOption('#city','北京市');await page.selectOption('#area','朝阳区');await page.click('#confirm-place');
 assert.equal(await page.locator('#sources').count(),0); await page.screenshot({path:path.join(artifacts,'build-home-mobile.png'),fullPage:true});
 await page.click('button[type=submit]');await page.waitForURL(/result.html/);assert.match(await page.textContent('#trip'),/屯溪区/);assert.equal(await page.locator('#cross-border').isVisible(),false);check('file:// 首页提交正确带入结果；同国不列跨境项');
 assert.match(await page.textContent('.decision'),/核实可行路线为 0/);assert.match(await page.textContent('.decision'),/这条我们还没核实，请以官方为准/);
 await page.screenshot({path:path.join(artifacts,'build-result-mobile.png'),fullPage:true});
 assert.equal(await page.evaluate(()=>location.search),'');
 await page.click('#edit');assert.match(await page.textContent('#origin-value'),/屯溪区/);assert.equal(await page.textContent('#pet-value'),'猫');check('返回修改恢复地点和宠物');
 await page.click('#destination');await page.selectOption('#country','CN');await page.selectOption('#city','黄山市（安徽省）');await page.selectOption('#area','屯溪区');await page.click('#confirm-place');await page.click('button[type=submit]');assert.match(await page.textContent('#form-error'),/相同/);check('相同地点阻止提交并明确提示');
 await page.click('#destination');await page.selectOption('#city','北京市');await page.click('#city-only');await page.click('button[type=submit]');await page.waitForURL(/result.html/);assert.equal(await page.locator('#area-gap').isVisible(),true);assert.match(await page.textContent('#trip'),/区 \/ 乡镇未填/);check('缺乡镇可继续，结果保留缺口');
 await page.click('#edit');await page.click('#destination');await page.selectOption('#country','FR');await page.fill('#place-search','不存在的小城');assert.match(await page.textContent('#search-status'),/还没收录/);
 await page.click('#missing-step summary');await page.fill('#manual-city','小城示例 <img src=x onerror=alert(1)>');await page.fill('#manual-area','乡镇示例');await page.click('#use-manual');await page.click('button[type=submit]');await page.waitForURL(/result.html/);
 assert.equal(await page.locator('#cross-border').isVisible(),true);assert.equal(await page.locator('#area-gap').isVisible(),true);assert.match(await page.textContent('#trip'),/手填，地点未核实/);assert.equal(await page.locator('#trip img').count(),0);assert.match(await page.textContent('#source-list'),/欧盟委员会/);check('缺小城可手填；跨境显示额外询问项；地名按文本安全渲染');
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async()=>{throw Error('denied')}},configurable:true}));await page.click('#copy');assert.match(await page.textContent('#copy-status'),/手动复制/);assert.equal(await page.evaluate(()=>document.getElementById('questions').selectionEnd>0),true);check('复制拒绝时选中文本并提示手动复制');
 await page.evaluate(()=>window.print=()=>{window.printCalled=true});await page.click('#print');assert.equal(await page.evaluate(()=>window.printCalled && document.getElementById('sources').open),true);await page.emulateMedia({media:'print'});assert.equal(await page.locator('#print').isVisible(),false);assert.equal(await page.locator('.tag').isVisible(),true);await page.emulateMedia({media:'screen'});check('打印展开来源并保留示例标签，隐藏操作按钮');
 await navigate(result);assert.match(await page.textContent('#trip'),/上海市/);check('直接打开结果为固定示例');
 await navigate(result+'#'+new URLSearchParams({pet:'cat',origin:JSON.stringify({country:['CN'],city:'上海市',area:'',manual:true}),destination:JSON.stringify({country:'CN',city:'北京市',area:'',manual:false})}));assert.equal(await page.textContent('#ready-state'),'请检查');
 await navigate(result+'#unknown=bad');assert.equal(await page.textContent('#ready-state'),'请检查');
 await navigate(result+'#pet=other&origin=bad');assert.match(await page.textContent('#ready'),/不完整/);assert.equal(await page.textContent('#ready-state'),'请检查');check('非法/不完整输入不显示绿色完整状态');
 const place=(country,city,area='')=>JSON.stringify({country,city,area,manual:false});
 const route=(pet,origin,destination)=>result+'#'+new URLSearchParams({pet,origin,destination});
 await navigate(route('dog',place('CN','上海市'),place('US','纽约市（纽约州）')));
 assert.match(await page.textContent('#rule-questions'),/申报回执/);assert.match(await page.textContent('#rule-provenance'),/us.cdc.dog.low-risk.receipt/);
 await navigate(route('cat',place('CN','上海市'),place('US','纽约市（纽约州）')));
 assert.doesNotMatch(await page.textContent('#rule-questions'),/申报回执/);assert.match(await page.textContent('#rule-questions'),/健康检查/);
 await navigate(route('cat',place('FR','巴黎（法兰西岛）'),place('FR','巴黎（法兰西岛）')));
 assert.equal(await page.locator('#rule-questions li').count(),0);
 await navigate(route('cat',place('US','纽约市（纽约州）'),place('CN','北京市')));
 assert.match(await page.textContent('#rule-provenance'),/cn.gacc.carried.health-certificate/);
 await navigate(route('cat',place('CN','上海市'),place('CN','北京市')));
 assert.equal(await page.locator('#rule-questions li').count(),0);check('规则按方向及犬猫筛候选；国内不套入境规则');
 await navigate(route('cat',place('US','纽约市（纽约州）'),place('FR','巴黎（法兰西岛）')));
 assert.match(await page.textContent('#rule-questions'),/等待期/);assert.match(await page.textContent('#rule-provenance'),/eu.ec.rabies.primary-wait/);
 await navigate(result+'#'+new URLSearchParams({pet:'cat',origin:JSON.stringify({country:'CN',city:'x'.repeat(61),area:'',manual:true}),destination:place('CN','北京市')}));
 assert.equal(await page.textContent('#ready-state'),'请检查');check('超长参数不静默截断或显示完整行程');
 await navigate(home); await page.click('button[type=submit]');assert.match(await page.textContent('#form-error'),/宠物/);assert.equal(await page.evaluate(()=>document.activeElement.id),'pet');
 await page.click('#origin');await page.selectOption('#country','US');await page.selectOption('#city','纽约市（纽约州）');assert.match(await page.textContent('#search-status'),/还没收录/);await page.click('#city-only');check('外国区乡镇缺失可继续；缺项错误聚焦');
 for(const width of [320,375,390,768]){
  await page.setViewportSize({width,height:844});await navigate(home);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.click('#origin');await page.selectOption('#country','CN');await page.selectOption('#city','黄山市（安徽省）');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.keyboard.press('Escape');await navigate(result);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await navigate(result+'#'+new URLSearchParams({pet:'cat',origin:JSON.stringify({country:'CN',city:'很长的小城地名'.repeat(7),area:'很长的乡镇'.repeat(8),manual:true}),destination:place('CN','北京市')}));
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await page.textContent('#ready-state'),'已填好');
 }
 check('320/375/390/768px 首页、弹层、长地名结果无横向溢出');
 await navigate(home);await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.id),'pet');await page.keyboard.press('Enter');assert.equal(await page.locator('#picker').isVisible(),true);await page.keyboard.press('Tab');await page.keyboard.press('Enter');assert.equal(await page.textContent('#pet-value'),'狗');check('键盘可打开弹层、遍历并选择宠物');
 const offline=await browser.newPage({javaScriptEnabled:false,viewport:{width:375,height:812}});await offline.goto(home);assert.equal(await offline.locator('noscript').isVisible(),true);await offline.goto(result);assert.match(await offline.textContent('noscript'),/固定示例/);check('无 JavaScript 明确告知仅可阅读固定示例');
 await page.setViewportSize({width:390,height:844});await navigate(home);
 for(const id of ['pet','origin','destination']) assert((await page.locator('#'+id).boundingBox()).height>=48);
 await page.click('#origin');await page.selectOption('#country','CN');await page.selectOption('#city','上海市');
 for(const id of ['country','city','area','close-picker']) assert((await page.locator('#'+id).boundingBox()).height>=48);check('手机触摸控件至少48px');
 await navigate(route('cat',place('US','纽约市（纽约州）'),place('FR','巴黎（法兰西岛）')));
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.copied=text}},configurable:true}));
 await page.fill('#questions','编辑后的咨询内容，最后一句必须保留。');await page.click('#copy');assert.match(await page.textContent('#copy-status'),/已复制/);assert.equal(await page.evaluate(()=>window.copied),'编辑后的咨询内容，最后一句必须保留。');check('复制成功使用用户编辑的全文');
 await page.evaluate(()=>window.dispatchEvent(new Event('beforeprint')));assert.equal(await page.locator('#sources').getAttribute('open'),'');
 await page.emulateMedia({media:'print'});assert.match(await page.textContent('#print-questions'),/最后一句必须保留/);assert.equal(await page.locator('#questions').isVisible(),false);
 await page.pdf({path:path.join(artifacts,'build-result-print.pdf'),format:'A4'});await page.emulateMedia({media:'screen'});check('浏览器打印保留完整编辑话术及来源');
 assert.deepEqual(remote,[]);check('用户页零网络请求');
 assert.deepEqual(errors,[]);check('上述交互无浏览器脚本错误');
 fs.writeFileSync(path.join(artifacts,'build-checks.json'),JSON.stringify({date:'2026-10-10',mode:'headless Chromium; file://',checks,errors},null,2)+'\n');
 console.log(JSON.stringify({passed:checks.length,errors},null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
